### PR TITLE
findHeads() handles graph cycles

### LINKED ISSUE #43: Recursion error in DependecyUtils
I found an error when using the DependencyUtils.  It seems like it's getting stuck in a loop in the dependency graph and the recursion blows the stack.  This is a snippet of the stack trace:

```
Caused by: java.lang.StackOverflowError
    at scala.runtime.BoxesRunTime.boxToInteger(BoxesRunTime.java:69)
    at edu.arizona.sista.processors.Sentence.dependencies(Document.scala:73)
    at edu.arizona.sista.utils.DependencyUtils$.getIncoming$2(DependencyUtils.scala:129)
    at edu.arizona.sista.utils.DependencyUtils$.followTrailOut$2(DependencyUtils.scala:145)
    at edu.arizona.sista.utils.DependencyUtils$.edu$arizona$sista$utils$DependencyUtils$$followTrail$3(DependencyUtils.scala:138)
    at edu.arizona.sista.utils.DependencyUtils$.followTrailOut$2(DependencyUtils.scala:150)
```

### PR DESCRIPTION
**Pull request by marcovzla**
This pull request reimplements `DependencyUtils.findHeads()` to handle cycles in the dependency graph.

It also reimplements `DependencyUtils.findHeadsStrict()` to call `findHeads()` instead of reimplementing graph traversal.

Fixes #43

### CODE REVIEW

**Comment by marcovzla** [comment]
Seems like this solution is still incomplete. Please don't merge yet.

**Comment by marcovzla** [comment]
There was still an issue if the root node had incoming edges, which sounds wrong to me but apparently it is possible. Added a test and a fix for that situation.

**Comment by myedibleenso** [comment]
Yeah, that sounds wrong to me, too.  Why would the root have anything incoming? It sounds like a red flag that the parse is wrong. Anyway, at least you're handling those cases.

**Comment by MihaiSurdeanu** [comment]
It can happen because the parser is dumb. It makes local decisions wo/ worrying about global coherence.

**Pull request merged**
