### PR TITLE
Add test file

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
@navalani, here is a framework to which one could add a bunch of rules for testing.  Use or not as you see fit and ask questions, of course.

**Comment by kwalcock** [comment]
This will work best if code is moved out of OdinStarter to Debugger or somewhere that can be shared.

**Comment by navalani** [comment]
Got it. Will get to it soon





Nick

**Review by navalani — APPROVED** [review]

**Comment by navalani** [comment]
Hey Keith,

I need some help transferring code from OdinStarter to the Debugger. If you
can brief me on what needs to be transferred, I can start working on it.
The HashMap in theThompsonVM can be transferred, but populating it is a
challenge.


Nick

**Comment by kwalcock** [comment]
@navalani, OdinStarter.visualize and OdinStarter.visualizeExtractor can be moved to Debugger.visualize and Debugger.visualizeExtractor and then they can be called from either OdinStarter or TestTokenExtractorDebugger.  It should be close to a copy and paste.

**Comment by navalani** [comment]
Done. Thanks

**Comment by navalani** [comment]
Also another clarifying question, in TestTokenExtractorDebugger, what is
a{1,3} in Rule("a and b", "a{1, 3} | b+") in line 56?
I was trying to make more complex rules by looking at the ones already in
there





Nick

**Comment by kwalcock** [comment]
@navalani, that's between 1 and 3 a`s`.  Be sure to check the LREC paper for tables of things like that.  It's mostly regex-like things.

**Comment by navalani** [comment]
Thanks, I will.

**Pull request merged**
