### PR TITLE
added charset param to ExtractorEngine

### PR DESCRIPTION
**Pull request by marcovzla**
Added `charset` parameter to `ExtractorEngine` (defaults to utf8).
Addresses clulab/reach#222

### CODE REVIEW

**Comment by marcovzla** [comment]
tests needed

**Comment by MihaiSurdeanu** [comment]
@marcovzla: One test fails. But it's unclear which one from the Travis log...

**Comment by marcovzla** [comment]
It is complaining about lack of memory:
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 506462208 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/travis/build/clulab/processors/hs_err_pid3321.log
```

I didn't change anything that would require more memory. I will rerun the tests on travis.

**Comment by marcovzla** [comment]
This keeps coming up. We need to merge this into master.
Any help writing the unit tests would be appreciated.
Or I will write them once I have time.

**Comment by myedibleenso** [comment]
We should probably add yet another constructor that takes a `String`, retrieves the corresponding `Charset`, and calls the constructor you've added here.

**Comment by myedibleenso** [comment]
## Test strategy
- Add 2-3 encoding variants of a `yaml` file to `test/resources`

**Comment by hickst** [comment]
Not yet finished. Cancelling until work is done.

**Pull request merged**
