### PR TITLE
Dev date modifiers

### PR DESCRIPTION
**Pull request by EgoLaparra**
This adds support to normalize date modifiers including `start`, `end`, `mid` and `approx`.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@EgoLaparra: this is great! Thank you! 
@kwalcock: can you please also take a quick look?
I think this is ready to merge.

**Review by kwalcock — APPROVED** [review]
I can't tell if it works, but it looks very professional.  Gold star and 😄

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !

@EgoLaparra : should I merge?

**Comment by kwalcock** [comment]
Yes, not that it looked at all bad before.  One day there will be a page about the local coding convention quirks.

**Comment by MihaiSurdeanu** [comment]
Merged. Thank you all!

**Pull request merged**
