### PR TITLE
Add a webapp

### PR DESCRIPTION
**Pull request by kwalcock**
This is still being fiddled with in order to make it reusable from other projects.  It is presently already useful in this project.

### CODE REVIEW

**Comment by kwalcock** [comment]
The webapp works now from webapp/run, from the docker container generated by dockerizeWebapp, and as a libraryDependency generated by publish or publishLocal.

**Comment by kwalcock** [comment]
See also the readme at  https://github.com/clulab/processors/tree/kwalcock/webapp/webapp.

**Comment by MihaiSurdeanu** [comment]
This is fantastic @kwalcock !
Very very useful.
My only comment is: is all the brat subdir needed? For example, it has a folder called "casestudies", which has a lot of content that doesn't seem necessary?

**Comment by kwalcock** [comment]
Good point!  I copied it over from Eidos without second thought.  It might have been superfluous even there.  I will check.

**Pull request merged**
