### PR TITLE
just testing this branch. do not merge

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@BeckySharp: can you please help with this?
It looks like `master.yml` is missing for the `RuleBasedEntityFinder`, but I don't remember deleting it... Can you please restore the needed grammar(s) in this branch?
Thanks and sorry for messing up!

```
[error] Caused by: sbt.ForkMain$ForkError: java.net.MalformedURLException: no protocol: org/clulab/openie/entities/grammar/master.yml
[error] 	at java.net.URL.<init>(URL.java:611)
[error] 	at java.net.URL.<init>(URL.java:508)
[error] 	at java.net.URL.<init>(URL.java:457)
[error] 	at org.clulab.odin.impl.RuleReader$.mkURL(RuleReader.scala:587)
[error] 	at org.clulab.odin.impl.RuleReader.readTaxonomy(RuleReader.scala:250)
[error] 	at org.clulab.odin.impl.RuleReader.$anonfun$rulesFromMasterFile$1(RuleReader.scala:60)
[error] 	at scala.Option.map(Option.scala:230)
[error] 	at org.clulab.odin.impl.RuleReader.rulesFromMasterFile(RuleReader.scala:60)
[error] 	at org.clulab.odin.impl.RuleReader.readMasterFile(RuleReader.scala:53)
[error] 	at org.clulab.odin.impl.RuleReader.read(RuleReader.scala:33)
[error] 	at org.clulab.odin.ExtractorEngine$.apply(ExtractorEngine.scala:87)
[error] 	at org.clulab.openie.entities.RuleBasedEntityFinder$.apply(RuleBasedEntityFinder.scala:220)
[error] 	at org.clulab.openie.IETestUtils$.<init>(IETestUtils.scala:12)
[error] 	at org.clulab.openie.IETestUtils$.<clinit>(IETestUtils.scala)
[error] 	at org.clulab.openie.filtering.TestStopWordManager.$anonfun$new$13(TestStopWordManager.scala:52)
[error] 	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
...
```

**Comment by MihaiSurdeanu** [comment]
@BeckySharp : can you please help here? See message above.

**Comment by BeckySharp** [comment]
> @BeckySharp : can you please help here? See message above.

sorry didnt see this til now, will address tonight

**Comment by BeckySharp** [comment]
@MihaiSurdeanu I think it must have been a sed or something bc in the taxonomy paths the word `taxonomy` had been replaced with `master`.  for future ref (and I had to look it up), the RBEF doesn't use a master file.  anyway, happy trails!

**Comment by MihaiSurdeanu** [comment]
Thanks @BeckySharp !!

**Pull request closed without merging**
