### PR TITLE
Update to support both 2.12 and 2.11

### PR DESCRIPTION
**Pull request by dispalt**
I made a couple non-functional changes, but then decided to not do the rest.  I would be happy to help, just wanted to make sure I was going down the right path.  With this command `release` will handle both `2.11` and `2.12`.  It's pinned to a SNAPSHOT of lum-ai/common, which I submitted a pr for https://github.com/lum-ai/common/pull/2

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thanks! This is great.

I suggest we wait with releasing a new version, until the lum.ai common project is released, so we don't depend on a snapshot. @marcovzla, @myedibleenso: when you have a moment, can you please review @dispalt's PR?

@hickst: does Reach work with Scala 2.12?

**Comment by dispalt** [comment]
Sorry I wasn't explicit, I fully expect to not merge this until there is a `2.12` release of lum.ai-common.  But just wanted to show you what I have so far.  The same team that runs this runs lum.ai correct?

**Comment by MihaiSurdeanu** [comment]
A subset of this team runs lum.ai, yes.

**Comment by marcovzla** [comment]
I just published common 0.0.8 for scala 2.11 and 2.12

**Comment by marcovzla** [comment]
Thanks @dispalt! LGTM

**Comment by dispalt** [comment]
Also before merging, are you fine with me increasing the default scala version to `2.11.11`?  Also I can squash the commits.

**Comment by marcovzla** [comment]
I'm ok with the upgrade. @MihaiSurdeanu? @hickst?

**Comment by MihaiSurdeanu** [comment]
me too.

**Comment by MihaiSurdeanu** [comment]
This seems to merge into master. @marcovzla: Ok with you?

**Comment by MihaiSurdeanu** [comment]
I meant: *seems Ok to merge*

**Comment by hickst** [comment]
@marcovzla Did you test this version of Processors with Reach?

**Comment by marcovzla** [comment]
no

**Comment by hickst** [comment]
I erased my Ivy cache, recompiled `master` and I get 55 compiler warnings. This one sounds the most potentially serious:
```[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:```

**Comment by dispalt** [comment]
I am not affiliated with the project but there is a dependency on some 2.10 library that I saw that would need to be upgraded (this was an issue in 2.11 too).  There's also a bunch of mutable usages that could be simplified to immutable (mostly inner looping in functions).  I tried to basically not do much outside of add the cross compilation infrastructure.  But would be happy to try and help clean up some of the code.

**Comment by hickst** [comment]
Hi Dan,
Yes, it's compiling for me, just getting a bunch of warnings; probably indicating things that we need to clean up for 2.12, (e.g., the new Eta-expansion warnings). Not sure which is the 2.10 library dependency but we are using some really old stuff (e.g. the XOM library which hasn't been updated since 2013).

**Comment by dispalt** [comment]
`nlptools-stem-morpha_2.10`, but yes lots of warnings.  You're really not even supposed to be able to depend on libraries like that, but I guess the bytecode its using hasn't changed much.  It would manifest as an abstract method error during runtime if the underlying code changed.

**Pull request merged**
