### PR TITLE
Speed up LexiconNER

### PR DESCRIPTION
**Pull request by kwalcock**
This PR is meant to provoke Travis into running unit tests.  Please do not merge yet.  It will be tested with reach next.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Do unit tests in Reach pass with this change?
Also, would it be possible to get times for "sbt main/test" in Reach before/after this change

**Comment by kwalcock** [comment]
It doesn't work with reach yet.  In one case reach skips the LexiconNER and goes directly for a HashTrie which I had eliminated.  I'm starting to put that back in so that reach builds without change.

FWIW there seems to be an existing compilation problem in HomeController that neither the build nor tests catch.

**Comment by kwalcock** [comment]
main/test running on processors 7.4.4 ran in 5:04 minutes just now with the original code, and 7.4.5-SNAPSHOT ran in 3:27 minutes with the new code.  I wasn't expecting that much of a difference.  Some more numbers will appear at #302.

**Comment by MihaiSurdeanu** [comment]
Nice!

I wonder what these numbers would look in Reach, assuming the same data structures are used?

**Comment by kwalcock** [comment]
I wasn't clear above.  The times are from reach's main/test when build.sbt is configured to use the old and new version of processors.  reach seems to use the BioCluProcessor which in turn uses the LexiconNER which has been rewritten.  The BioCluProcessor is what I have been timing in processors as well via a new test case.  The intention is that it is ready to go and reach will be faster after the merge and republishing of processors and then an update to the dependency in reach.  There are a couple of other PRs ready for processors that should also go in.

**Comment by kwalcock** [comment]
If someone needs/wants to test how this might affect some application of reach on some corpus, then doing a publishLocal on this branch (kwalcock-DuoHashTrie) and then changing reach's main/build.sbt procVer to 7.4.5-SNAPSHOT should do the trick.

**Comment by MihaiSurdeanu** [comment]
Thanks! Last question: if you run runAllTests.sh in reach, do all tests pass?

**Comment by kwalcock** [comment]
Yes, they do.

**Comment by MihaiSurdeanu** [comment]
Cool. Then merge?

**Comment by kwalcock** [comment]
If you please.  #295 and #305 should also be merged before the next release.  I'm not sure about the others.

**Comment by MihaiSurdeanu** [comment]
Done. Can you please update the CHANGES file (let’s use as next version 7.5.0), and release?

**Pull request merged**
