### PR TITLE
Added new tests on numbers and range numbers

### PR DESCRIPTION
**Pull request by hubert10**
Hi Mihai,

I added some tests on numbers and range numbers. Thanks

Hubert

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thanks! I will probably get to this only tomorrow, due to other obligations...

**Comment by hubert10** [comment]
Hi Mihai,

Thanks for the comments on tests, could you please point out which
dedicated grammar you usually use for parsing range numbers?

Thanks

Hubert

**Comment by MihaiSurdeanu** [comment]
Hi @hubert10,
The grammar for number ranges is in this branch, which has not been merged yet:
https://github.com/clulab/processors/tree/hubert-meas-units-tests

More exactly, here:
https://github.com/clulab/processors/blob/hubert-meas-units-tests/main/src/main/resources/org/clulab/numeric/number-ranges.yml

Once we merge it, which should be soon, we can revisit number ranges.

**Comment by hubert10** [comment]
Understood. Thanks.

**Pull request merged**
