### PR TITLE
Improved collapsing of nmod in enhanced universal dependencies

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by kwalcock** [comment]
@MihaiSurdeanu, the result of running the Eidos tests with this version of CluProcessor are pasted below.  I'll do another diff on some outputs in case something pops out.

[info] Run completed in 1 minute, 23 seconds.
[info] Total number of tests run: 399
[info] Suites: completed 41, aborted 0
[info] Tests: succeeded 305, failed 94, canceled 0, ignored 176, pending 0
[info] *** 94 TESTS FAILED ***
[error] Failed tests:
[error]         org.clulab.wm.eidos.text.cag.TestCagP2
[error]         org.clulab.wm.eidos.text.eval6.TestDoc3
[error]         org.clulab.wm.eidos.text.raps.TestRaps1
[error]         org.clulab.wm.eidos.text.raps.TestRaps
[error]         org.clulab.wm.eidos.text.eval6.TestDoc5
[error]         org.clulab.wm.eidos.text.cag.TestCagP6
[error]         org.clulab.wm.eidos.sameas.TestSimpleSameAs
[error]         org.clulab.wm.eidos.text.cag.TestCagP3
[error]         org.clulab.wm.eidos.text.cag.TestCagP0
[error]         org.clulab.wm.eidos.text.eval6.TestDoc2
[error]         org.clulab.wm.eidos.text.eval6.TestDoc8
[error]         org.clulab.wm.eidos.text.cag.TestEidosMention
[error]         org.clulab.wm.eidos.text.TestUnicode
[error]         org.clulab.wm.eidos.text.cag.TestCagP4
[error]         org.clulab.wm.eidos.text.eval6.TestDoc7
[error]         org.clulab.wm.eidos.rule.TestJointAdjectives
[error]         org.clulab.wm.eidos.test.TestTest
[error]         org.clulab.wm.eidos.text.cag.TestCagP1
[error] (core/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 87 s, completed May 10, 2018 1:36:19 PM

**Comment by kwalcock** [comment]
In CluProcessor.parse(doc:Document), the code

```scala
  /** Syntactic parsing; modifies the document in place */
  def parse(doc:Document) {
    basicSanityCheck(doc)
    if (doc.sentences.head.tags.isEmpty)
      throw new RuntimeException("ERROR: you have to run the POS tagger before parsing!")
    if (doc.sentences.head.lemmas.isEmpty)
      throw new RuntimeException("ERROR: you have to run the lemmatizer before parsing!")
```
is expecting the document to have some sentences.  We've got some texts with lists that result in a document containing characters \x20\xA0.  The resulting document contains no sentences and then the program crashes on doc.sentences.head.  It can use a nonEmpty check of some kind.
```scala
if (doc.sentences.length > 0) {
```

**Comment by MihaiSurdeanu** [comment]
Good catch, @kwalcock!
Can I volunteer you to fix it? :)

**Comment by kwalcock** [comment]
I expected that, but with insufficient conviction to proceed without a mandate :)  See the forthcoming PR #243.

**Pull request merged**
