### PR TITLE
Replace collection.filter.isEmpty with !collection.exists

### PR DESCRIPTION
**Pull request by kwalcock**
This is for RuleBasedEntityFinders with supporting methods added to State

### CODE REVIEW

**Comment by kwalcock** [comment]
See #492

**Comment by kwalcock** [comment]
This changes some very old code by @myedibleenso, so perhaps he can better recognize whether it might now be broken.

**Review by MihaiSurdeanu — APPROVED** [review]

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !

**Comment by BeckySharp** [comment]
@myedibleenso can still check but I think it's safe changes

**Pull request merged**
