### PR TITLE
Propagate case setting to IntHashTrie

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
I *hope* this is the extent of the problem.  Thank you, @gcgbarbosa, for finding it.  If the LexiconNERShell should make it to master, then this branch can be merged with lexner and the result merged to master.  If not, then I should make a separate PR on master with just this change.

**Review by gcgbarbosa — APPROVED** [review]

**Comment by gcgbarbosa** [comment]
@kwalcock thanks a lot!

**Review by MihaiSurdeanu — APPROVED** [review]

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !

I think we need to release processors, and update reach, because this bug impacts reach. When you have a chance, can you please do it?

**Comment by kwalcock** [comment]
Processors is republished.  Reach is to follow.  Sorry about the bug.  It's probably not the only one.

**Comment by MihaiSurdeanu** [comment]
Thank you!

**Pull request merged**
