### PR TITLE
Parser improvements: slimmer models + Eisner algorithm over unlabeled dependencies

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@kwalcock : can you please let me know what the error is here? I lost my login for jenkins.
Thanks!

**Comment by MihaiSurdeanu** [comment]
Fwiw, this works locally.

**Comment by kwalcock** [comment]
It's not compiling.  It may only be happening for Scala 2.11 which doesn't like trailing commas, like at line 75.

```
[info] Compiling 193 Scala sources and 5 Java sources to /var/jenkins_home/workspace/processors_deps-topk@2/main/target/scala-2.11/classes ...
Waiting for lock on /var/jenkins_home/.sbt/boot/scala-2.12.7/org.scala-sbt/sbt/1.2.8/sbt.components.lock to be available...
[error] /var/jenkins_home/workspace/processors_deps-topk@2/main/src/main/scala/org/clulab/processors/clu/CluProcessor.scala:76:5: illegal start of simple expression
[error]     )
[error]     ^
[error] /var/jenkins_home/workspace/processors_deps-topk@2/main/src/main/scala/org/clulab/processors/clu/CluProcessor.scala:77:3: ')' expected but '}' found.
[error]   }
[error]   ^
[error] two errors found
[error] (main / Compile / compileIncremental) Compilation failed
[error] Total time: 15 s, completed Mar 20, 2022 2:15:50 AM
```

**Comment by MihaiSurdeanu** [comment]
I’m not at a computer now. Can you please see if you can fix it, if you’re
in front of one? If not, I’ll fix it later.

**Comment by kwalcock** [comment]
I can get it.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !
I think we should release 8.4.8 now. There are many good changes in this release.

**Pull request merged**
