### PR TITLE
Make seasons configurable

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This is still a draft because I want to figure out why in one case a / is needed and in another not.  I'm also going to include a test case to make sure it works.  I still have to connect this to CluProcessor with one line.

**Comment by MihaiSurdeanu** [comment]
so far so good :)

**Comment by kwalcock** [comment]
This was probably @EgoLaparra 's plan in the first place, but here's my version, no longer a draft.

**Comment by EgoLaparra** [comment]
https://github.com/clulab/processors/blob/59f2979a6b6fb1fbdeaef8c8b81cf1aba3025ac4/main/src/test/scala/org/clulab/numeric/TestSeasonNormalizer.scala#L10
What a poetic unit test! 

Looks great. Thank you, Keith.

**Review by EgoLaparra — APPROVED** [review]

**Comment by kwalcock** [comment]
@EgoLaparra, does your branch need to go to master now, or is there still more to do?  I don't see a PR yet.

**Comment by EgoLaparra** [comment]
@kwalcock, we have to include more grammars for time expressions with seasons.

**Comment by kwalcock** [comment]
@EgoLaparra: Thanks.  I wasn't aware of that.  Whatever and whenever you and Mihai decide.

**Pull request merged**
