### PR TITLE
StopWord handling

### PR DESCRIPTION
**Pull request by BeckySharp**
Added FileUtils, StopWordManaging, and StopWordManager from eidos.

@MihaiSurdeanu and @kwalcock -- moved FileUtils to processors, there is some redundancy with Files I think.
Also we've talked about a clucommon... anyway, here is stuff!! :)

### CODE REVIEW

**Review by MihaiSurdeanu — APPROVED** [review]
Nice!

**Comment by BeckySharp** [comment]
FYI @MihaiSurdeanu and @kwalcock as soon as this is merged, I'll go back to eidos to use these (tagset, stopword stuff, fileutils) from here instead of having them there

**Comment by MihaiSurdeanu** [comment]
Done!

**Comment by BeckySharp** [comment]
ok -- on second thought, I should wait to do what I said (use the processors versions of these things in eidos) until 8.3.3 is released.  no worries, I'll work on moving `discovery` stuff in the meantime. thanks!

**Pull request merged**
