### PR TITLE
Allow compilation and run with up to Java 18

### PR DESCRIPTION
**Pull request by kwalcock**
This does not up the version on Stanford NLP, however.  That will be a separate PR after the tests pass and will necessitate incrementing the version number substantially.

### CODE REVIEW

**Comment by kwalcock** [comment]
See also #612 for more information.  No special flags are needed for Java now.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock ! Ready to merge, as far as I can tell.

**Comment by kwalcock** [comment]
There may be unintended side effects, but merging now will help us find them before the release to maven.

**Comment by kwalcock** [comment]
@BeckySharp, you might be interested in this PR.  Things like --add-opens java.base/sun.net.[www.protocol.jar](http://www.protocol.jar/)=ALL-UNNAMED should no longer be needed.

**Pull request merged**
