### PR TITLE
Add json4StopGraph output from ProcessorJsonShell

### PR DESCRIPTION
**Pull request by kwalcock**
Try "sbt runMain org.clulab.processors.ProcessorJsonShell"

### CODE REVIEW

**Comment by kwalcock** [comment]
Here is some sample output:
```json
[ {
  "Tokens" : [ [ "The", 0 ], [ "wives", 1 ], [ "recognize", 2 ], [ "that", 3 ], [ "if", 4 ], [ "they", 5 ], [ "want", 6 ], [ "to", 7 ], [ "have", 8 ], [ "a", 9 ], [ "more", 10 ], [ "secure", 11 ], [ "economic", 12 ], [ "existence", 13 ], [ ",", 14 ], [ "they", 15 ], [ "have", 16 ], [ "to", 17 ], [ "encourage", 18 ], [ "their", 19 ], [ "husbands", 20 ], [ "to", 21 ], [ "go", 22 ], [ "to", 23 ], [ "France", 24 ], [ ".", 25 ] ],
  "Chunks" : [ [ "B-NP", 0 ], [ "I-NP", 1 ], [ "B-VP", 2 ], [ "B-SBAR", 3 ], [ "B-SBAR", 4 ], [ "B-NP", 5 ], [ "B-VP", 6 ], [ "I-VP", 7 ], [ "I-VP", 8 ], [ "B-NP", 9 ], [ "I-NP", 10 ], [ "I-NP", 11 ], [ "I-NP", 12 ], [ "I-NP", 13 ], [ "O", 14 ], [ "B-NP", 15 ], [ "B-VP", 16 ], [ "I-VP", 17 ], [ "I-VP", 18 ], [ "B-NP", 19 ], [ "I-NP", 20 ], [ "B-VP", 21 ], [ "I-VP", 22 ], [ "B-PP", 23 ], [ "B-NP", 24 ], [ "O", 25 ] ],
  "Start_character_offsets" : [ 0, 4, 10, 20, 25, 28, 33, 38, 41, 46, 48, 53, 60, 69, 78, 80, 85, 90, 93, 103, 109, 118, 121, 124, 127, 133 ],
  "End_character_offsets" : [ 3, 9, 19, 24, 27, 32, 37, 40, 45, 47, 52, 59, 68, 78, 79, 84, 89, 92, 102, 108, 117, 120, 123, 126, 133, 134 ],
  "Basic_syntactic_dependencies" : [ [ 1, 0, "det" ], [ 2, 1, "nsubj" ], [ 2, 16, "ccomp" ], [ 2, 25, "punct" ], [ 6, 4, "mark" ], [ 6, 5, "nsubj" ], [ 6, 8, "xcomp" ], [ 8, 7, "mark" ], [ 8, 13, "dobj" ], [ 11, 10, "advmod" ], [ 13, 9, "det" ], [ 13, 11, "amod" ], [ 13, 12, "amod" ], [ 16, 3, "mark" ], [ 16, 6, "advcl" ], [ 16, 14, "punct" ], [ 16, 15, "nsubj" ], [ 16, 18, "xcomp" ], [ 18, 17, "mark" ], [ 18, 20, "dobj" ], [ 18, 22, "xcomp" ], [ 20, 19, "nmod:poss" ], [ 22, 21, "mark" ], [ 22, 24, "nmod" ], [ 24, 23, "case" ] ],
  "Enhanced_syntactic_dependencies" : [ [ 1, 0, "det" ], [ 2, 1, "nsubj" ], [ 2, 16, "ccomp" ], [ 2, 25, "punct" ], [ 5, 8, "nsubj:xsubj" ], [ 6, 4, "mark" ], [ 6, 5, "nsubj" ], [ 6, 8, "xcomp" ], [ 8, 5, "nsubj" ], [ 8, 7, "mark" ], [ 8, 13, "dobj" ], [ 11, 10, "advmod" ], [ 13, 9, "det" ], [ 13, 11, "amod" ], [ 13, 12, "amod" ], [ 15, 18, "nsubj:xsubj" ], [ 15, 22, "nsubj:xsubj" ], [ 16, 3, "mark" ], [ 16, 6, "advcl" ], [ 16, 14, "punct" ], [ 16, 15, "nsubj" ], [ 16, 18, "xcomp" ], [ 18, 15, "nsubj" ], [ 18, 17, "mark" ], [ 18, 20, "dobj" ], [ 18, 22, "xcomp" ], [ 20, 19, "nmod:poss" ], [ 22, 21, "mark" ], [ 22, 24, "nmod_to" ], [ 24, 23, "case" ] ],
  "Semantic_dependencies" : [ [ 2, 1, "A0" ], [ 2, 3, "A1" ], [ 6, 5, "A0" ], [ 6, 7, "A1" ], [ 8, 5, "A0" ], [ 8, 13, "A1" ], [ 13, 5, "A1" ], [ 13, 12, "A1" ], [ 18, 15, "A0" ], [ 18, 16, "AM-MOD" ], [ 18, 20, "A1" ], [ 18, 21, "Ax" ], [ 20, 19, "A1" ], [ 22, 20, "A1" ], [ 22, 23, "Ax" ] ],
  "Enhanced_semantic_dependencies" : [ [ 2, 1, "A0" ], [ 2, 16, "A1" ], [ 6, 5, "A0" ], [ 6, 8, "A1" ], [ 8, 5, "A0" ], [ 8, 13, "A1" ], [ 13, 5, "A1" ], [ 13, 12, "A1" ], [ 18, 15, "A0" ], [ 18, 16, "AM-MOD" ], [ 18, 20, "A1" ], [ 18, 22, "Ax_to" ], [ 20, 19, "A1" ], [ 22, 20, "A1" ], [ 22, 24, "Ax_to" ] ]
}, {
  "Tokens" : [ [ "That", 0 ], [ "'s", 1 ], [ "all", 2 ], [ "folks", 3 ], [ ".", 4 ] ],
  "Chunks" : [ [ "B-NP", 0 ], [ "B-VP", 1 ], [ "B-NP", 2 ], [ "I-NP", 3 ], [ "O", 4 ] ],
  "Start_character_offsets" : [ 136, 140, 143, 147, 152 ],
  "End_character_offsets" : [ 140, 142, 146, 152, 153 ],
  "Basic_syntactic_dependencies" : [ [ 3, 0, "nsubj" ], [ 3, 1, "cop" ], [ 3, 2, "det" ], [ 3, 4, "punct" ] ],
  "Enhanced_syntactic_dependencies" : [ [ 3, 0, "nsubj" ], [ 3, 1, "cop" ], [ 3, 2, "det" ], [ 3, 4, "punct" ] ],
  "Semantic_dependencies" : [ ],
  "Enhanced_semantic_dependencies" : [ ]
} ]
```

**Comment by kwalcock** [comment]
The formatter results in very long lines that wrap around the screen so that reading is difficult.  The alternative vertical wrapping has its own problems.  It wasn't obvious how to change it, so perhaps others can return feedback so that I know how long to work on that setting.

**Comment by MihaiSurdeanu** [comment]
Thank you @kwalcock ! Let me email Paul for feedback.

**Comment by kwalcock** [comment]
I'm merging then based on the email.

**Pull request merged**
