### PR TITLE
travis cache

### PR DESCRIPTION
**Pull request by marcovzla**
Trying out travis cache as suggested in #257

### CODE REVIEW

**Comment by kwalcock** [comment]
P.S.  If it helps at all, the effect probably won't be seen until the second build.  The first build will likely be slower as it has to fetch all the dependencies as normal plus write them all back out to the cache.

**Comment by MihaiSurdeanu** [comment]
I'd like to see performance differences on this. I'll play with this.
Should we merge this?

**Comment by kwalcock** [comment]
You'll probably want to build/test again.  Click "Show all checks" below and have Travis perform the same thing again and check the time.

**Comment by MihaiSurdeanu** [comment]
The first-time test completed in ~59 mins.

build1

Now running the second one.

**Comment by MihaiSurdeanu** [comment]
I don't think this is working. The second test ran in the same time:

screen shot 2018-08-17 at 7 40 23 am

**Comment by MihaiSurdeanu** [comment]
Well, maybe it downloaded all the dependencies in the 1:30 min of difference? Possible.
In any case, this is not a major speedup.

**Comment by kwalcock** [comment]
It does seem like it used the cache, but then to less effect than desired.  I guess the mileage varied.  It seemed worth a try.

**Comment by MihaiSurdeanu** [comment]
We could keep it... It helps a bit, and it doesn't hurt.

**Comment by marcovzla** [comment]
Closing this since it hasn't been touched in a while.
Feel free to reopen.

**Pull request closed without merging**
