### PR TITLE
First Construction of rules for recignizing data in European/American data format. 

### PR DESCRIPTION
**Pull request by vanh17**
Added 2 rules for American date format.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@vanh17: thanks! But I don't see any unit tests for these new dates in the American format. Can you please:
a) Merge the `numeric_processor` into yours again with:
```
git checkout numeric_processor
git pull
git checkout hoang_numeric_processor
git merge numeric_processor
```
this is necessary because we fixed the failing tests that Jenkins complains about here.

b) Then add new unit tests for your dates here: `main/src/test/scala/org/clulab/numeric/TestDateRecognition.scala`
c) Commit and push to your branch.
d) Then come back here and make sure that the "All checks have failed" has disappeared. Then let me know.

Thanks!

**Comment by vanh17** [comment]
@MihaiSurdeanu, all tests passed now! Please let me know when you approve it or if you have any questions! Thank you!

**Comment by MihaiSurdeanu** [comment]
nice @vanh17 !

Merged, and branch deleted. Please start by branching again off `numeric_processor`

**Comment by MihaiSurdeanu** [comment]
I suggest starting by adding unit tests, even if some fail. Then start addressing them one by one.

**Pull request merged**
