### PR TITLE
Added support for number, date, and measurement recognition to CluProcessor

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@vanh17 , @marcovzla : the NumericProcessor is now in master.

@kwalcock : can you please release 8.4.4

**Comment by MihaiSurdeanu** [comment]
Thank you!

**Comment by kwalcock** [comment]
Yes.

**Comment by MihaiSurdeanu** [comment]
thanks!

**Comment by kwalcock** [comment]
It is at maven and should be available imminently.

**Comment by MihaiSurdeanu** [comment]
Thanks!


On July 15, 2021 at 7:01:59 PM, Keith Alcock ***@***.***)
wrote:

It is at maven and should be available imminently.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/processors/pull/529#issuecomment-880817236>, or
unsubscribe

**Pull request merged**
