### PR TITLE
Added case restoration to CluProcessor

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by hubert10** [comment]
@kwalcock, do you know why this resource **mtl-en-case-e1e2e3.x2i** is missing on processors? I remember to have pulled the last commit and published it locally, see below `[error] (Compile / runMain) java.io.FileNotFoundException: Could not find resource "org/clulab/processors/clu/mtl-en-case-e1e2e3.x2i".
`
I am just running case restoring on habitus. Thanks

**Comment by MihaiSurdeanu** [comment]
@hubert10 : this is a file I added to processors-models v0.2.4. Maybe you're using the previous version?

@kwalcock : this is ready to merge in master. Thanks!

**Comment by hubert10** [comment]
I am not sure I know how to check the  processors-models version, but I
think I am using the latest version. Thanks!

**Comment by kwalcock** [comment]
@hubert10, I was surprised to see the same thing when using IntelliJ.  Apparently using the locally published processors with the same version number but a different transient dependency for the models is something that IntelliJ can't follow.  At the bottom of the Project pane you should see a list of External Libraries.  In it should be sbt:org.clulab.processors-models:0.2.4.jar.  It should not be the old 0.2.3.  The "Reload All sbt Projects" button alone does not seem to help.  To fix it, I edited build.sbt to remove the processors and eidos dependencies, reloaded the sbt project so that the models were not in the list, then put the dependencies back in, and finally made sure that the models version was updated.  Then it worked.  I hope you can follow that.

**Comment by hubert10** [comment]
Okay, thanks, I'll give it a try. Thank you.

**Comment by kwalcock** [comment]
At the meeting @hubert10 reported getting the error message even with `sbt`.  The command to find out which dependencies sbt is using is `dependencyTree`.  If you type that at the `sbt` prompt (`sbt:habitus`), one of the many lines of output should be
```
[info]   | |   |   +-org.clulab:processors-models:0.2.4 [S]
```

**Comment by kwalcock** [comment]
Mihai OK'd this merge above and in the meantime I have not heard that it was the cause of the configuration problem, so I will press the button.  restoreCase is not part of the standard annotation procedure, so any adverse effects are only delivered on demand.

**Comment by MihaiSurdeanu** [comment]
Thanks!
Is now a good time to release 8.5.0? Or do you have other fixes to be merged?

**Comment by kwalcock** [comment]
I should get Hubert's case-restoring branch with TextLabelToCoNLLU in there, related to #617.  It needs a little sorting out.  I'm not sure what to do with #547.  I could disable the failing tests, for example.

The parallel load #622 can wait a little.  I'd like to make sure it plays well with clients that might be multi-threaded themselves. 
 #606 with artifactory has to be postponed.  Although https was working for most clients, Jenkins could not use it to access Artifactory from behind the proxy on river so that testing would fail.  I have to work that out with Eric.

**Comment by MihaiSurdeanu** [comment]
I am not sure #617 is still needed?
On #547: @hubert10, can you please identify which of these tests pass? We should comment out the failing ones (or mark them to be ignored), and merge the rest. I think these are useful.

**Comment by kwalcock** [comment]
I think this is ready to be published now.

**Comment by MihaiSurdeanu** [comment]
Thanks! Will you publish it?

**Comment by kwalcock** [comment]
It's ready.  A habitus update is soon to follow

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock!

**Pull request merged**
