### PR TITLE
Update documentation on processors page

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock ! Looks great.

**Comment by kwalcock** [comment]
On the installation page I'd make a distinction between installing for use with Maven and for SBT.  Some people might think that both somehow apply at the same time.

**Comment by MihaiSurdeanu** [comment]
Good idea! You want to do it, or should I?

**Comment by BeckySharp** [comment]
+1 for you two, thanks for caring so deeply about the quality of your library and its users!

**Comment by kwalcock** [comment]
I need to describe having Maven get the http artifacts.  Plus the tests failed and need to be looked at.  Eric from the lab was going to help with arranging for https.

**Comment by kwalcock** [comment]
This is working now.  I'd like to save changes to the installation page for a different PR and go ahead and merge this one.

**Pull request merged**
