### PR TITLE
Added support for MTL in the dependency parser. Removed the RST discourse parser. This should be 8.4.0.

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@kwalcock: this PR contains my improvements to the CLUProcessor parser. Can you please run the runtime experiments again (but remove the SRL part, which we know is slow)?

Also, these tests consistenly run OOM with `sbt test`, even though I increased memory to 10g in .sbtopts. Can you please check?
```
[error] 	org.clulab.processors.TestParallel
[error] 	org.clulab.processors.TestRepeatability
[error] 	org.clulab.processors.TestFastNLPProcessor
[error] 	org.clulab.processors.TestProcessorThreading
```

**Comment by MihaiSurdeanu** [comment]
I am releasing processors-models, which is needed by this. I will ping you when done.

**Comment by MihaiSurdeanu** [comment]
I am getting this error when I try to release processors-models:
```
[error] Unable to find credentials for [Artifactory Realm @ artifactory.cs.arizona.edu].
[error] java.io.IOException: Server returned HTTP response code: 401 for URL: http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release-local/org/clulab/processors-models/0.1.10/processors-models-0.1.10.pom
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
[error] 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
[error] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
[error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:285)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
...
[error] (publish) java.io.IOException: Server returned HTTP response code: 401 for URL: http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release-local/org/clulab/processors-models/0.1.10/processors-models-0.1.10.pom
[error] Total time: 39 s, completed Jun 9, 2021 1:31:48 PM
[error] Invalid programmatic input:
[error] Expected ';'
[error] --failure--
[error]            ^
```

@kwalcock : can you please help? The repo (wo the model files, which are too large) is here:
https://github.com/clulab/processors-models

Thanks!

**Comment by kwalcock** [comment]
build.sbt says
```
credentials += Credentials(Path.userHome / ".sbt" / ".credentials")
```
Do you have that file?  It may be on some other machine.  It does look like you have a matching account for it at http://artifactory.cs.arizona.edu:8081.

**Comment by MihaiSurdeanu** [comment]
I don't on this machine. Can you release it for me?
I can package the model files so you can include them in the release, if you can do it.
Thanks!

**Comment by kwalcock** [comment]
If I can get to the large files somehow, then I can release.  Otherwise, the credentials file should look like
```
realm=Artifactory Realm
host=artifactory.cs.arizona.edu
user=msurdeanu
password=<API key>
```
and you would just need to log on and get or generate an API key.

**Comment by MihaiSurdeanu** [comment]
Sorry, log in where?
Thanks!

**Comment by kwalcock** [comment]
http://artifactory.cs.arizona.edu:8081

**Comment by MihaiSurdeanu** [comment]
Can you please reset the password for me?


On June 9, 2021 at 8:20:26 PM, Keith Alcock ***@***.***)
wrote:

http://artifactory.cs.arizona.edu:8081

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/processors/pull/501#issuecomment-857884411>, or
unsubscribe

**Comment by kwalcock** [comment]
The tests all ran OK for me.  However, I don't trust .sbtopts or its
documentation and think it works differently on Windows.  I suspect it
determines how much memory sbt gets to do its work and not how much it in
turn gives Java to run tests.  Instead, I use an
export _JAVA_OPTIONS="-Xmx10g -Dfile.encoding=UTF-8".  If something like
that works, it should be possible to make it the default value when running
tests.  sbt has some settings for it.

**Comment by MihaiSurdeanu** [comment]
Thanks!

Can this be made default in sbt across platforms without setting the env
var?

**Comment by MihaiSurdeanu** [comment]
Fwiw, your artifactory instructions for the API key worked. Thank you!

**Comment by kwalcock** [comment]
Here are times for the new branch, spans, and the one it would replace, master.  The parse is now about 1/2 the srl time where before it was even a little bit more.  It's about twice as fast as before.


||spans|spans|master|master|
|---|---|---|---|---|
chunking|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000|
clear|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000|
discourse|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000|
lemmatize|0:00:00:00.329|0:00:00:00.379|0:00:00:00.247|0:00:00:00.732|
parse|0:00:01:27.160|0:00:01:38.177|0:00:03:21.687|0:00:03:10.730|
recognizeNamedEntities|0:00:00:36.075|0:00:00:38.503|0:00:00:34.024|0:00:00:30.979|
resolveCoreference|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000|
srl|0:00:02:55.855|0:00:03:11.869|0:00:02:44.514|0:00:02:35.171|
tagPartsOfSpeech|0:00:00:45.543|0:00:00:48.863|0:00:00:48.393|0:00:00:41.303|

**Comment by MihaiSurdeanu** [comment]
Thanks!

**Comment by kwalcock** [comment]
I tracked down the previous timing program which tries to prime the pipeline so that everything is initialized before the timers start and it processes each of 10 files 10 times.  This is what it got.  That the srl time varies so much seems strange.

stage|spans-CluProcessor|spans-FastNLPProcessor|master-CluProcessor
|:--|--:|--:|--:|
chunking|0:00:00:00.000|0:00:04:20.419|0:00:00:00.000
clear|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000
discourse|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000
lemmatize|0:00:00:00.521|0:00:00:00.397|0:00:00:00.408
parse|0:00:03:43.415|0:00:01:02.749|0:00:09:24.660
recognizeNamedEntities|0:00:01:44.508|0:00:02:56.378|0:00:01:32.847
relationExtraction||0:00:00:00.003|
resolveCoreference|0:00:00:00.000|0:00:00:00.000|0:00:00:00.000
srl|0:00:11:53.362|0:00:13:01.950|0:00:09:46.176
tagPartsOfSpeech|0:00:01:53.214|0:00:00:05.515|0:00:01:42.234
total|19.25038694|21.45693306|22.43879033

**Comment by MihaiSurdeanu** [comment]
Thanks Keith! I would call this a success. Just FYI, the `tagPartsOfSpeech` method in CluProcessor actually includes functionality for `chunking`, which is handled separately in FastNLP.

**Comment by MihaiSurdeanu** [comment]
When do you want to release this? Wait for the new fatdynet with the CLAB and parallelism updates?

**Comment by kwalcock** [comment]
I would separate the major changes.  The parallelism will probably require changes in clients, at least to the initialization.  I published this one locally and eidos seems to have passed.

**Comment by MihaiSurdeanu** [comment]
Ok!


On June 11, 2021 at 9:15:13 AM, Keith Alcock ***@***.***)
wrote:

I would separate the major changes. The parallelism will probably require
changes in clients, at least to the initialization. I published this one
locally and eidos seems to have passed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/processors/pull/501#issuecomment-859303007>, or
unsubscribe

**Comment by kwalcock** [comment]
This is being merged and then soon released.

**Comment by MihaiSurdeanu** [comment]
Thanks!

The release will include Becky's PR, right?

**Comment by kwalcock** [comment]
Yes.  Maybe it needs an entry in CHANGES then.

**Comment by MihaiSurdeanu** [comment]
Yes. @BeckySharp: can you please update CHANGES for your PR?

**Comment by BeckySharp** [comment]
> Yes. @BeckySharp: can you please update CHANGES for your PR?

yes, on it now

**Comment by BeckySharp** [comment]
> Yes. @BeckySharp: can you please update CHANGES for your PR?

done in #503

**Comment by BeckySharp** [comment]
@MihaiSurdeanu in the documentation you should also remove this:

**Comment by kwalcock** [comment]
It was published.

**Comment by MihaiSurdeanu** [comment]
Thanks! I cleaned up the documentation.

**Pull request merged**
