### PR TITLE
PT Lemmas + new models

### PR DESCRIPTION
**Pull request by gcgbarbosa**
### Lemmas

- Included [LemPort](https://github.com/rikarudo/LemPORT) in processors
- Mapped LemPort tagset to UD tagset
- Implemented cheap lemmas to be used as features for chunking and POS
- Added a new parameter **lang** to PartOfSpeechTagger and Chunking classes to allow for Portuguese training with cheap lemmas

##### Expanded ADVP:
```
Muito adv B-ADVP
mais adv I-ADVP
do_que conj-s I-ADVP
```
to:
```
Muito ADV B-ADVP
mais ADV I-ADVP
de ADP I-ADVP
o PRON I-ADVP
que PRON I-ADVP
```
##### Expanded and corrected PROPN/N
`Pesquisa_Datafolha n B-NP`
to:
```
Pesquisa PROPN B-NP
Datafolha PROPN I-NP
```
(last fix had not taken into account NOUN tokens)

#### Parsing/POS data changes

Brackets and quotes were transformed to match **processors** TokenizerStepNormalization.scala transformations acording with this [file](https://gist.github.com/gcgbarbosa/cd2009b23929458a36ce6a08acd716e9#file-gsd-pud-processors-quotes-py).

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@gcgbarbosa: can you please take a look at the conflicts in this PR?

**Comment by gcgbarbosa** [comment]
Yep. I will take a look next week.

**Comment by gcgbarbosa** [comment]
@MihaiSurdeanu It seems to be ok.

**Comment by MihaiSurdeanu** [comment]
@gcgbarbosa: just checking, you have merged in the latest master branch, correct?

**Comment by gcgbarbosa** [comment]
@MihaiSurdeanu, correct.

**Comment by MihaiSurdeanu** [comment]
Thanks, merged. Can you please adjust the changes file to reflect these changes?

**Comment by gcgbarbosa** [comment]
I had missed your message. I added this to my TODOs.

**Pull request merged**
