### PR TITLE
Add a comment related to a bug

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
@MihaiSurdeanu, this shows the failing tests, but the branch can/will otherwise be deleted.  Testing will probably work again now.

**Comment by kwalcock** [comment]
I can fix the bug, but you may prefer to.

**Comment by MihaiSurdeanu** [comment]
Can you please fix it, if you can?

**Comment by kwalcock** [comment]
Will do.

**Pull request closed without merging**
