### PR TITLE
Sbt upgrade

### PR DESCRIPTION
**Pull request by myedibleenso**
## Summary of changes
- Upgraded `sbt` to next major version (`v0.13.x` -> `v1.x`)
- Support GPG v2 for release signing

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Looks good, but tests are failing...

**Comment by kwalcock** [comment]
These tests ended with out of memory errors.

**Comment by mslinn** [comment]
It would be so nice to merge this PR.

**Comment by MihaiSurdeanu** [comment]
All these make sense, but we still have the OOM error. Maybe reverting back to -J-Xmx5500M in .sbtopts would help? @marcovzla, what do you think?

**Comment by mslinn** [comment]
6GB RAM is a tiny amount for this type of application.

**Comment by marcovzla** [comment]
I agree it would be nice to merge this PR. Upgrading sbt would simplify things for me.
We haven't done so because Travis runs out of memory when executing the unit tests.
See https://travis-ci.org/clulab/processors/jobs/499513609#L2673
We wanted to figure out a way to decrease the memory consumption so that we can still use Travis, but no one is working on it as I know.

**Comment by mslinn** [comment]
Seems like this PR is simple and straightforward. It works. If Travis is getting in the way, why not stop using it? Otherwise this project remains frozen in time, which would be a shame.

**Comment by MihaiSurdeanu** [comment]
@marcovzla: does this PR pass if you set -J-Xmx5500M?

**Comment by marcovzla** [comment]
It doesn't. I can take a look again next week.

**Comment by MihaiSurdeanu** [comment]
@marcovzla, @myedibleenso, @mslinn: This was merged in master through a different branch. Our unit tests have been switched from Travis to Jenkins, where we have more RAM.

**Pull request merged**
