### PR TITLE
Put clulab in charge of its own holidays

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Nice, thank you @kwalcock !

**Comment by kwalcock** [comment]
I think this is good enough for now.  It gives us access to newer holidays even though it uses an older JollyDay, and we can (and have) added our own holidays.  The HolidayNormalizer should be multiple times faster because it doesn't go through holidays of every separate state and it matches based on keys rather than descriptions, which are an extra call away.

**Comment by kwalcock** [comment]
P.S. This should prevent eidos from crashing while processing habitus files and SEC software from crashing on interviews.

**Review by MihaiSurdeanu — APPROVED** [review]
Thanks!

**Pull request merged**
