### PR TITLE
fixed a bug in the parsing of ordinal numbers

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@kwalcock : Ok, this time we are ready to release 8.4.5. Thanks!

**Comment by kwalcock** [comment]
Acknowledged.  I'm working on it.

**Comment by kwalcock** [comment]
I'm not sure this PR or the next one (#534 & #535) finished testing before it was merged.  There is no checkmark anywhere and local tests of master after both PRs complain about org.clulab.processors.TestCluProcessor:
```
Parsing is fine.
[info] - should parse text correctly
[info] - should create semantic dependencies of the correct length
WORDS: Foods, such, as, icecream, are, tasty, .
WORDS: There, was, famine, due, to, drought, .
[info] - should parse MWEs correctly
[info] - should recognize dates
[info] - should recognize date ranges *** FAILED ***
[info]   "2021-01-12 -[-] 2022-02-XX" was not equal to "2021-01-12 -[] 2022-02-XX" (TestCluProcessor.scala:184)
[info] - should recognize custom names entities

[info] Tests: succeeded 11, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	org.clulab.processors.TestCluProcessor
```

**Comment by MihaiSurdeanu** [comment]
Oh... My bad. Can you please adjust this test? The separator between the two dates is now "--" rather than a single hyphen.

**Comment by kwalcock** [comment]
This ordinalfix branch was deleted, but it seems to have a lot in common with hybridodin that I see dangling.  Has hybridodin been fully incorporated and is it therefore candidate for deletion?  With squash and merge I can't immediately tell.

**Pull request merged**
