### PR TITLE
Autogeneration of odin grammar documentation

### PR DESCRIPTION
**Pull request by BeckySharp**
OK, I(REALLY)DK how to test this.... but this PR adds the ability for the RuleReader to generate two diff documentations automatically.

NOTE: MUCH of this code was written by @jastier -- I wish there was a better way to credit him in this PR than just mentioning him :/

The first is a view that is based on the Rules, one block per rule.
The second view aggregate this information by Type of Mention (i.e., _label_).
Each generated file is a markdown file.

entrypoints in RuleReader:
- `exportRuleSchemasFromMaster`
- `exportRuleSchemasFromSimple`
- `exportExtractionSchemasFromMaster`
- `exportExtractionSchemasFromSimple`

### Here is a sample of the Rule view:

# Odin Rule Schemas
--------

#### rule: _agree_token_match_

attribute | value
-----  |   ---- 
type | `TokenExtractor`
labels    | [`Agreement`, `Communicate`, `SimpleActions`, `Action`, `EventLike`, `Concept`]
priority  | `2`
keep      | `true`

&nbsp;

--------

#### rule: _agreement2_

attribute | value
-----  |   ---- 
type | `TokenExtractor`
labels    | [`Agreement`, `Communicate`, `SimpleActions`, `Action`, `EventLike`, `Concept`]
priority  | `2`
keep      | `true`

&nbsp;

--------

**argument name** | **label(s)** | **quantifier** | **required?**
:---- | :---- | :---- | :----
 source | `Concept` | `?` | `false` 
 target | `Concept` | `?` | `false` 

&nbsp;

--------

### And here's a sample of the Extraction view:

# Odin Extraction Schemas
----------------------------------

###  You

|Attribute        |  Value | 
| :--------       | :---- |
|rules            | _you_token_capture_ 
|label hierarchy  | [`You`, `Entity`, `Concept`] 
|priorities       | `1`
|keep             | `true` 

_No arguments_

----------------------------------

###  ChangePriority

|Attribute        |  Value | 
| :--------       | :---- |
|rules            | [_change_priority2_, _change_priority_] 
|label hierarchy  | [`ChangePriority`, `ComplexActions`, `Action`, `EventLike`, `Concept`] 
|priorities       | `3+`
|keep             | `true` 
|actions | `removeResearcher`

_Arguments_
|name        | **label(s)**  | **quantifier(s)** | **required?**|
| :--------  | :----         | :----             | :---- 
| _target_ | [`Victim`, `Person`] | _none_ | `true`
| _person_ | [`Entity`, `Entity`] | `?` | `false`

----------------------------------

###  MakeCommitment

|Attribute        |  Value | 
| :--------       | :---- |
|rules            | _commit_to_something_ 
|label hierarchy  | [`MakeCommitment`, `Commitment`, `ComplexActions`, `Action`, `EventLike`, `Concept`] 
|priorities       | `7+`
|keep             | `true` 
|actions | `removeResearcher`

_Arguments_
|name        | **label(s)**  | **quantifier(s)** | **required?**|
| :--------  | :----         | :----             | :---- 
| _target_ | [`Action`] | _none_ | `true`
| _person_ | [`Self`] | `?` | `false`

----------------------------------

### CODE REVIEW

**Comment by BeckySharp** [comment]
FYI @jastier  @adarshp @remo-help

**Review by MihaiSurdeanu — APPROVED** [review]
LGTM!

**Comment by BeckySharp** [comment]
@kwalcock if you need me to add tests please let me know what they should look like.  I'm hesitant to add soemthing and it be like "I expect the string to == this" bc that's kinda a bad test, but other than that I am at a loss.
Otherwise, if we don't need tests, then this is done.

**Comment by adarshp** [comment]
This is great, thank you @jastier and @BeckySharp !

**Comment by jastier** [comment]
Thank you Becky!

**Comment by MihaiSurdeanu** [comment]
@kwalcock: imo, this can be merged.

**Comment by kwalcock** [comment]
Thanks for adding the test.  I'd like to dub it the safety blanket test.  It makes me feel more secure.  More to follow...

**Comment by kwalcock** [comment]
Thanks also for the uncommas ;-)

**Comment by kwalcock** [comment]
This seems like a great idea.  I really like that there is no additional library dependency to deal with.  It might could (double modal verb construction (c) @kwalcock) do with a MarkdownTable class, but some other time.  I will eventually add a
```scala
class Test extends FlatSpec with Matchers
```
somewhere so that it doesn't need to be repeated ad infinitum.  This seems not too many steps away from generating Scala code in addition to the markdown.  I look forward to thinking about what might be done with that.  If nobody has second thoughts, I will merge shortly.

**Review by kwalcock — APPROVED** [review]

**Comment by kwalcock** [comment]
I didn't notice any `main` that generates documentation, so it probably belongs to the projects that use processors.  The test earns bonus points if it demonstrates how they should go about it.  It seems to. +1

**Pull request merged**
