### PR TITLE
NumberParser

### PR DESCRIPTION
**Pull request by marcovzla**
First version of the number parser.
Only parses integers, but returns doubles.
Handles phrases such as `one thousand nine hundred ninety nine` but not `nineteen ninety nine`.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Nice! Thanks @marcovzla !

**Comment by marcovzla** [comment]
I see that something failed, but I can't login into jenkins to see what it is.

**Comment by BeckySharp** [comment]
@marcovzla 
```
Skip to content
[Jenkins]Jenkins
search
CluLab
log out
Jenkins
processors
numparser
#4

Back to Project

Status

Changes

Console Output

View as plain text

View Build Information

Git Build Data

Embeddable Build Status

Pipeline Steps

Previous Build
FailedConsole Output
Push event to branch numparser
20:08:53 Connecting to https://api.github.com using kwalcock/******
Obtained jenkinsfile from 7db10157b220ed1298430c70018f8feccdfb7e36
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/jenkins_home/workspace/processors_numparser
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
using credential 372071f6-d203-41a7-b41d-dfb7aeb742a2
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/clulab/processors.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/clulab/processors.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --no-tags --progress https://github.com/clulab/processors.git +refs/heads/numparser:refs/remotes/origin/numparser
Checking out Revision 7db10157b220ed1298430c70018f8feccdfb7e36 (numparser)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 7db10157b220ed1298430c70018f8feccdfb7e36
Commit message: "array"
 > git rev-list --no-walk 6401d3e331511784339b1a2963294e6320170477 # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Test)
[Pipeline] ansiColor
[Pipeline] {
[Pipeline] echo
Testing...
[Pipeline] sh
+ sbt +test
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Picked up _JAVA_OPTIONS: -Xmx10g
[info] Loading settings for project processors_numparser-build from plugins.sbt ...
[info] Loading project definition from /var/jenkins_home/workspace/processors_numparser/project
[info] Loading settings for project root from build.sbt,release.sbt,compile.sbt,test.sbt,version.sbt,publish.sbt ...
[info] Loading settings for project openie from build.sbt ...
[info] Loading settings for project corenlp from build.sbt ...
[info] Loading settings for project main from build.sbt,test.sbt ...
[info] Set current project to root (in build file:/var/jenkins_home/workspace/processors_numparser/)
[info] Setting Scala version to 2.11.12 on 4 projects.
[info] Reapplying settings...
[info] Set current project to root (in build file:/var/jenkins_home/workspace/processors_numparser/)
[info] Compiling 179 Scala sources and 5 Java sources to /var/jenkins_home/workspace/processors_numparser/main/target/scala-2.11/classes ...
[error] /var/jenkins_home/workspace/processors_numparser/main/src/main/scala/org/clulab/numeric/NumberParser.scala:141:3: illegal start of simple expression
[error]   )
[error]   ^
[error] /var/jenkins_home/workspace/processors_numparser/main/src/main/scala/org/clulab/numeric/NumberParser.scala:143:1: ')' expected but '}' found.
[error] }
[error] ^
[error] two errors found
[error] (main / Compile / compileIncremental) Compilation failed
[error] Total time: 12 s, completed Jun 15, 2021 8:09:22 PM
[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE
REST API
Jenkins 2.249.3

**Comment by MihaiSurdeanu** [comment]
I'll take a look

**Comment by kwalcock** [comment]
Processors is compiled with both Scala 2.12 and 2.11, so those trailing commas that you are so fond of don't work.  :-(

**Comment by marcovzla** [comment]
Thanks! I'll remove them

**Comment by kwalcock** [comment]
```
[info] TestEntityConstraints:
[info] Uneven parentheses
[info] org.clulab.openie.entities.TestEntityConstraints *** ABORTED ***
[info]   java.lang.ExceptionInInitializerError:
[info]   at org.clulab.openie.entities.TestEntityConstraints$$anonfun$1.apply(TestEntityConstraints.scala:16)
[info]   at org.clulab.openie.entities.TestEntityConstraints$$anonfun$1.apply(TestEntityConstraints.scala:14)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
[info]   at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
[info]   ...
[info]   Cause: java.net.MalformedURLException: no protocol: org/clulab/openie/entities/grammar/master.yml
[info]   at java.net.URL.<init>(URL.java:593)
[info]   at java.net.URL.<init>(URL.java:490)
[info]   at java.net.URL.<init>(URL.java:439)
[info]   at org.clulab.odin.impl.RuleReader$.mkURL(RuleReader.scala:587)
[info]   at org.clulab.odin.impl.RuleReader.org$clulab$odin$impl$RuleReader$$readTaxonomy(RuleReader.scala:250)
[info]   at org.clulab.odin.impl.RuleReader$$anonfun$1.apply(RuleReader.scala:60)
[info]   at org.clulab.odin.impl.RuleReader$$anonfun$1.apply(RuleReader.scala:60)
[info]   at scala.Option.map(Option.scala:146)
[info]   at org.clulab.odin.impl.RuleReader.rulesFromMasterFile(RuleReader.scala:60)
[info]   at org.clulab.odin.impl.RuleReader.readMasterFile(RuleReader.scala:53)
[info]   ...
[error] Uncaught exception when running org.clulab.openie.entities.TestEntityConstraints: java.lang.ExceptionInInitializerError
[error] sbt.ForkMain$ForkError: java.lang.ExceptionInInitializerError: null
[error] 	at org.clulab.openie.entities.TestEntityConstraints$$anonfun$1.apply(TestEntityConstraints.scala:16)
[error] 	at org.clulab.openie.entities.TestEntityConstraints$$anonfun$1.apply(TestEntityConstraints.scala:14)
[error] 	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[error] 	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:22)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:20)
[error] 	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[error] 	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[error] 	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
[error] 	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
[error] 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[error] 	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
[error] 	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[error] 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[error] 	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
[error] 	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
[error] 	at org.scalatest.Suite$class.run(Suite.scala:1147)
[error] 	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
[error] 	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[error] 	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
[error] 	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
[error] 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[error] 	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: sbt.ForkMain$ForkError: java.net.MalformedURLException: no protocol: org/clulab/openie/entities/grammar/master.yml
[error] 	at java.net.URL.<init>(URL.java:593)
[error] 	at java.net.URL.<init>(URL.java:490)
[error] 	at java.net.URL.<init>(URL.java:439)
[error] 	at org.clulab.odin.impl.RuleReader$.mkURL(RuleReader.scala:587)
[error] 	at org.clulab.odin.impl.RuleReader.org$clulab$odin$impl$RuleReader$$readTaxonomy(RuleReader.scala:250)
[error] 	at org.clulab.odin.impl.RuleReader$$anonfun$1.apply(RuleReader.scala:60)
[error] 	at org.clulab.odin.impl.RuleReader$$anonfun$1.apply(RuleReader.scala:60)
[error] 	at scala.Option.map(Option.scala:146)
[error] 	at org.clulab.odin.impl.RuleReader.rulesFromMasterFile(RuleReader.scala:60)
[error] 	at org.clulab.odin.impl.RuleReader.readMasterFile(RuleReader.scala:53)
[error] 	at org.clulab.odin.impl.RuleReader.read(RuleReader.scala:33)
[error] 	at org.clulab.odin.ExtractorEngine$.apply(ExtractorEngine.scala:87)
[error] 	at org.clulab.openie.entities.RuleBasedEntityFinder$.apply(RuleBasedEntityFinder.scala:220)
[error] 	at org.clulab.openie.IETestUtils$.<init>(IETestUtils.scala:12)
[error] 	at org.clulab.openie.IETestUtils$.<clinit>(IETestUtils.scala)
[error] 	at org.clulab.openie.entities.TestEntityConstraints$$anonfun$1.apply(TestEntityConstraints.scala:16)
[error] 	at org.clulab.openie.entities.TestEntityConstraints$$anonfun$1.apply(TestEntityConstraints.scala:14)
[error] 	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[error] 	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:22)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:20)
[error] 	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[error] 	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[error] 	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
[error] 	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
[error] 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[error] 	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
[error] 	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[error] 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[error] 	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
[error] 	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
[error] 	at org.scalatest.Suite$class.run(Suite.scala:1147)
[error] 	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
[error] 	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
[error] 	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[error] 	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
[error] 	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
[error] 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[error] 	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[info] TestCustomizableRuleBasedEntityFinder:
[info] org.clulab.openie.entities.TestCustomizableRuleBasedEntityFinder *** ABORTED ***
[info]   java.net.MalformedURLException: no protocol: org/clulab/openie/entities/grammar/master.yml
[info]   at java.net.URL.<init>(URL.java:593)
[info]   at java.net.URL.<init>(URL.java:490)
[info]   at java.net.URL.<init>(URL.java:439)
[info]   at org.clulab.odin.impl.RuleReader$.mkURL(RuleReader.scala:587)
[info]   at org.clulab.odin.impl.RuleReader.org$clulab$odin$impl$RuleReader$$readTaxonomy(RuleReader.scala:250)
[info]   at org.clulab.odin.impl.RuleReader$$anonfun$1.apply(RuleReader.scala:60)
[info]   at org.clulab.odin.impl.RuleReader$$anonfun$1.apply(RuleReader.scala:60)
[info]   at scala.Option.map(Option.scala:146)
[info]   at org.clulab.odin.impl.RuleReader.rulesFromMasterFile(RuleReader.scala:60)
[info]   at org.clulab.odin.impl.RuleReader.readMasterFile(RuleReader.scala:53)
[info]   ...
```

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !

This does not seem @marcovzla fault... Do we know who made these changes in the entities grammar?  @BeckySharp, do you know?

**Comment by kwalcock** [comment]
I'm retesting master in case something is just messed up.

**Comment by MihaiSurdeanu** [comment]
Thank you!


On June 16, 2021 at 9:35:57 AM, Keith Alcock ***@***.***)
wrote:

I'm retesting master in case something is just messed up.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/processors/pull/510#issuecomment-862088915>, or
unsubscribe

**Comment by kwalcock** [comment]
Master is fine.  I was misled by the small number of commits and didn't see a problem in them.  This is a PR into a different branch which might not be passing itself.  It's usually left to the owner of the branch to accept or not.  The owner might be you, so carry on.

**Comment by BeckySharp** [comment]
Do you guys need me to check something out still?

**Comment by MihaiSurdeanu** [comment]
The error is not from this branch, so merging.

**Comment by MihaiSurdeanu** [comment]
Hey @marcovzla: small issue: I am using two spaces as indentation in processors. Can you please follow the same protocol in the future? Sorry, just my OCD.... I already adjusted the NumberParser, so no need to reopen this.
See also: https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by marcovzla** [comment]
jajaja ok I will use two spaces in the future :)

**Pull request merged**
