### PR TITLE
Overlap NamedEntities more carefully

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
@maxaalexeeva, would you like to try this out to see if it fixes the problems you were seeing with the locally published master branch?  This lets longer custom named entities overwrite shorter ones.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !

**Comment by kwalcock** [comment]
I tried this out on Habitus and it did fix the problems.  Habitus with processor master failed 11 tests and after this fix they all went away except for the one that specifically tests for the incorrect behavior.  I'm ready to merge unless @maxaalexeeva has objections.  It's probably a good time to republish as well so we don't get used to the bug in the currently published version.

**Comment by maxaalexeeva** [comment]
@kwalcock thank you! Sorry didn't get to this yet - had to get a couple other things out the way. If tests in main now pass, it's most likely good, but I can check in a couple of hours.

**Comment by kwalcock** [comment]
@maxaalexeeva, waiting is easy enough :-)  Want to be sure it's working the way you expect it to.  It's TestHabitusProcessor behavior of "acronym" that will fail because it is checking for the incorrect behavior.

**Comment by maxaalexeeva** [comment]
@kwalcock I have not found any additional issues! Thank you!

**Comment by maxaalexeeva** [comment]
@kwalcock let me know when you release processors and I'll adjust habitus main (in addition to changes to autocloser and lazy ner, there are a bunch of tests that are supposed to pass with the new processors and I will want to go through them, see if they actually pass)

**Comment by kwalcock** [comment]
@maxaalexeeva, will do.  There are updates to *.md files which means it will take a couple of hours still.

**Pull request merged**
