### PR TITLE
Use kryo for serialization

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Nice! But tests are failing.

**Comment by kwalcock** [comment]
Passing now

**Comment by MihaiSurdeanu** [comment]
Nice! Merge?
Did you release the artifactory with the binary embeddings?

**Comment by kwalcock** [comment]
This uses the kryo version of glove, which is deployed.  The text version is no longer included as a dependency.

**Pull request merged**
