### PR TITLE
Use Stanford CoreNLP 3.9.2

### PR DESCRIPTION
**Pull request by polymorpher**
The current package use Stanford CoreNLP 3.8.0. Some new wrappers are introduced in CoreNLP 3.9, which makes extracting information a lot easier (and substantially reduced type confusions from IntelliJ). There are also several model and multilingual improvements. Even though clulab/processors doesn't support languages other than English at this time, it is not hard for end-users (like me) to implement them. And it would be a lot easier to make our projects depend on clulab/processors rather than adding CoreNLP dependencies separately.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@marcovzla, @kwalcock: this sounds like a necessary upgrade. Any strong reasons to postpone it? I am in favor of making this change for v8.0.0.

**Comment by kwalcock** [comment]
The failing tests need to be looked into:
```
[info] *** 1 SUITE ABORTED ***
[info] *** 26 TESTS FAILED ***
[error] Failed tests:
[error] 	org.clulab.processors.TestCoreNLPProcessor
[error] 	org.clulab.processors.TestFastNLPProcessorSpeed
[error] 	org.clulab.processors.TestCoreNLPSentimentAnalyzer
[error] 	org.clulab.serialization.TestDocumentSerializer
[error] 	org.clulab.processors.TestShortestPath
[error] 	org.clulab.processors.TestCoreNLPCoref
[error] 	org.clulab.processors.TestCoreNLPNER
[error] 	org.clulab.processors.TestFastNLPProcessor
[error] 	org.clulab.processors.TestProcessorThreading
[error] Error during tests:
[error] 	org.clulab.processors.TestOpenIE
```


They seem to be all of the kind
```
[info] CoreNLPProcessor
[info] - should not crash *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at edu.stanford.nlp.pipeline.NERCombinerAnnotator.annotate(NERCombinerAnnotator.java:321)
[info]   at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
[info]   at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:637)
[info]   at org.clulab.processors.shallownlp.ShallowNLPProcessor.recognizeNamedEntities(ShallowNLPProcessor.scala:230)
[info]   at org.clulab.processors.Processor.annotate(Processor.scala:90)
[info]   at org.clulab.processors.Processor.annotate$(Processor.scala:87)
[info]   at org.clulab.processors.shallownlp.ShallowNLPProcessor.annotate(ShallowNLPProcessor.scala:34)
[info]   at org.clulab.processors.TestCoreNLPCoref.$anonfun$new$1(TestCoreNLPCoref.scala:17)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```

**Comment by MihaiSurdeanu** [comment]
@marcovzla : I believe you ran into this before. do you remember what the solution was? Or should I look at this?

**Comment by polymorpher** [comment]
I spent some time debugging. This https://github.com/clulab/processors/pull/360/commits/3a7b5e0dc7914fe603d260242ba1613f61cc3557  seems to have fixed it. I am not sure if it breaks other things. By using the constructor that takes annotated sentences to create an Annotation, other annotations are automatically set (tokens, text), thereby setting a correct structure to CoreNLPDocument.annotation which is assumed in the tests to be holding (Some) non-null values on itself and for the annotations within

**Comment by polymorpher** [comment]
Also getting this 
```
14:11:41.349 [pool-17-thread-11-ScalaTest-running-TestCoreNLPProcessor] ERROR e.s.nlp.pipeline.StanfordCoreNLP - Attempted to fetch annotator "parse" but the annotator pool does not store any such type!
```

**Comment by polymorpher** [comment]
https://github.com/clulab/processors/pull/360/commits/b61a97bb6e6d3a9270785b9f43656a56c065c34a is in response to this error

```
[info] TestCoreNLPNER:
[info] CoreNLP
[info] - should recognize NEs correctly in 1 sentence *** FAILED ***
[info]   "[COUNTRY]" was not equal to "[LOCATION]" (TestCoreNLPNER.scala:19)
[info] - should recognize NEs correctly in 2 sentences *** FAILED ***
[info]   "[COUNTRY]" was not equal to "[LOCATION]" (TestCoreNLPNER.scala:45)
```

"COUNTRY" is better than "LOCATION" so I updated the test

**Comment by polymorpher** [comment]
Updated ShallowNLPProcessor.docToAnnotation in https://github.com/clulab/processors/pull/360/commits/f4f1e8c5e43f9c54d72b587a213cc1577d9d399b to manually add doc-level token and text annotations, instead of using constructor from Stanford CoreNLP as in https://github.com/clulab/processors/pull/360/commits/3a7b5e0dc7914fe603d260242ba1613f61cc3557

The only remaining tests that are failing are in `TestCoreCharacterOffsets.scala`:
```
[info] - should generate correct character offsets in multiple sentences *** FAILED ***
[info]   beginPosition: 24 endPosition: 29 "[There]" did not equal "[here,]" (TestCoreCharacterOffsets.scala:49)
[info] - should generate correct character offsets in a file *** FAILED ***
[info]   "[The]" did not equal "[he ]" (TestCoreCharacterOffsets.scala:70)
```
There seems to be an off-by-one error.

**Comment by MihaiSurdeanu** [comment]
Thanks @polymorpher !
I am beginning to look at these changes. I hope to merge them soon.
I need to fix a minor bug in the processors tokenizer, and then I think we can release 8.0.0.

Btw, please note that now all our processors, including the CoreNLP derived ones, using our in-house tokenizer. So you might notice some minor differences if you compare the CoreNLPProcessor output with the Stanford one.

**Comment by MihaiSurdeanu** [comment]
This PR has been moved to PR #361.
Closing this one.

**Pull request closed without merging**
