### PR TITLE
Scala 3

### PR DESCRIPTION
**Pull request by kwalcock**
This will be checked some more, but I want to see what the server thinks of it already.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
LGTM @kwalcock !
Thanks for doing all this work!

**Comment by kwalcock** [comment]
The backlog of processors updates is getting complicated enough that this needs to be merged.  The related release, coming soon, might be 8.6.0.

**Comment by MihaiSurdeanu** [comment]
Ok. I will merge some additions to the number parser soon.

**Comment by kwalcock** [comment]
If this causes merge conflicts, I can work on them then.

**Pull request merged**
