### PR TITLE
adding unit classes

### PR DESCRIPTION
**Pull request by maxaalexeeva**
unit entities are returned with a more specific class label, e.g., MEASUREMENT-`AREA`, MEASUREMENT-`DURATION`

Note: some units don't have a class; in that case, they are just `MEASUREMENT`

### CODE REVIEW

**Comment by maxaalexeeva** [comment]
@kwalcock the tests don't seem to be running?

**Comment by kwalcock** [comment]
I saw that.  Maybe they were just slow to start.

**Review by kwalcock — APPROVED** [review]
LGTM.  Shortest review yet!

**Comment by kwalcock** [comment]
This may be needed for a SEC update.  The resulting master would need to be published, either to maven or artifactory.

**Comment by kwalcock** [comment]
Does @MihaiSurdeanu think it's OK?

**Comment by MihaiSurdeanu** [comment]
LGTM too!

**Pull request merged**
