### PR TITLE
Test the ambivalenceHash

### PR DESCRIPTION
**Pull request by kwalcock**
Please do not merge yet.  This PR is so that Travis runs the tests which do not work on my computer.

### CODE REVIEW

**Comment by kwalcock** [comment]
This change is discussed in issue #294.  It has been unit and regression tested in Eidos and unit tested in Processors.  equivalenceHash remains, but there is a new ambivalenceHash in Document and Sentence that is used to calculate the hashCode of a Mention.

**Comment by MihaiSurdeanu** [comment]
This is fine, but I wonder if we can make it even faster. "words" are a deterministic transformation of "raw", so they are strictly not needed in the hash, if you have "raw" in there...

**Comment by kwalcock** [comment]
Yes, that can be updated.  I was on the fence about it.  The transformation may be subject to change, but probably not on the timescale of sentence comparisons.  It will probably not make a lot of difference in performance which is probably more the result of caching.  PR momentarily.

**Comment by kwalcock** [comment]
I'm seeing a complaint on an Eidos serialization test.  Please don't merge yet.

**Comment by kwalcock** [comment]
That was my bad.  By using this.getClass.getName I was ruling out subclass objects from having the same hash.  Eidos needs to compare an EidosDocument to a Document.  However, rather than using a fixed stringCode as in the other cases, I went with Document.getClass.getName so that refactoring will work.  It should be OK now when Travis completes.

**Pull request merged**
