### PR TITLE
Portuguese and Spanish processor improvements

### PR DESCRIPTION
**Pull request by danebell**
All Portuguese and Spanish part-of-speech and parsing models have improved training and testing:

- Contractions are removed from training files.
- Separate tests are administered per test corpus.
- Part-of-speech models are BiMEMM
- Tests of SpanishCluProcessor have been added.

Additionally, Spanish tokenization and sentence splitting have been implemented:

- Spanish- (and Catalan-)specific characters have been added to the word forms, and are protected from normalization to non-accented equivalents.
- Common Spanish abbreviations and sentence-starts are enumerated to improve sentence splitting.
- Spanish contractions `del` and `al` are each split into their constituents

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Hi @danebell: this looks good, but checks are failing in travis. Can you please check?

Also, did you implement those steps we discussed about removing contractions? If so, it seems to me that the LAS/UAS scores are still very low, more than 10% lower than English...

**Comment by danebell** [comment]
@MihaiSurdeanu Yes, I did remove contractions for both Spanish and Portuguese. I'm not sure how to resolve the low scores. One possibility is to slightly expand the training set by using the PUD corpus for training instead of testing. Since it is only a testing set, I have only used it for testing so far. But it's not that large at 1000 sentences, so I doubt it would raise the score by 10%.

**Comment by marcovzla** [comment]
is this pr ready to be merged?

**Comment by MihaiSurdeanu** [comment]
Yes! I thought this was merged...
I'll merge this.

**Comment by MihaiSurdeanu** [comment]
Hold on. There are some conflicts here. I'll work with @gcgbarbosa to fix them.

**Comment by MihaiSurdeanu** [comment]
Ok, @gcgbarbosa and I solved the conflicts.
If tests pass, I will merge soon.

**Comment by MihaiSurdeanu** [comment]
Hey @kwalcock and/or @marcovzla: we are getting time out errors on tests that would succeed given more time. Any solutions other than making our unit tests smaller?

**Comment by marcovzla** [comment]
Can you point us to a test where that happens?

**Comment by MihaiSurdeanu** [comment]
It happened here, but the timer reseted after I typed a new comment...
I think a major reason why this happens is because of the cross build for 2.11 and 2.12, which effectively doubles the test time.

**Comment by MihaiSurdeanu** [comment]
In any case, this branch is now merged in master.
When should we release a new processors?

**Comment by marcovzla** [comment]
I think this was a travis issue: https://twitter.com/traviscistatus/status/1027937440340664320

I think we should play a little bit with the portuguese stuff in eidos webapp to convince ourselves all is good. Maybe later today?

**Comment by MihaiSurdeanu** [comment]
@gcgbarbosa: can you please help @marcovzla review the PT tools in processors before we release?

**Comment by gcgbarbosa** [comment]
Sure. I am doing it right now @MihaiSurdeanu.

**Comment by kwalcock** [comment]
@MihaiSurdeanu, @marcovzla, if there are dependencies, it might help to have Travis cache them (to Amazon S3) and retrieve them from there rather than wherever they usually come from.  Eidos has these additional lines in travis.yml, which seemed to help that project.  YMMV though.  It seems like a corrupted cache can sometimes breaks the build, so heads up.
```
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.ivy2
    - $HOME/.m2
    - $HOME/.sbt
```

**Comment by marcovzla** [comment]
Thanks @kwalcock!
I will try this out. It currently takes around half an hour for travis to finish, so any speedup would be nice.

**Pull request merged**
