### PR TITLE
Get Artifactory into the POM file

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This PR add a few lines

```scala
pomIncludeRepository := { (repo: MavenRepository) =>
  repo.root.startsWith("http://artifactory.cs.arizona.edu")
}
```
 into the build.sbt file of processors-main which result in this additional output in the POM file when processors-main is published:

```xml
    <repositories>
        <repository>
            <id>Artifactory</id>
            <name>Artifactory</name>
            <url>http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release/</url>
            <layout>default</layout>
        </repository>
    </repositories>
```
This seems to be enough information for maven to figure out how to load processors-models for projects that depend on that.  It should not be necessary for such (maven) projects to worry about the transitive dependency.  sbt, however, does not seem to be as smart and was once documented as such.  I'm still testing, though, to verify.

**Comment by MihaiSurdeanu** [comment]
Awesome @kwalcock !

Please ping when I can release.

**Comment by kwalcock** [comment]
It indeed doesn't appear to help the situation with sbt.  With maven it at least *seemed* to: I could trick it into working.  By all accounts so far, the PR doesn't make things worse, though.  I'd go ahead and release with fingers slightly crossed.

**Comment by MihaiSurdeanu** [comment]
Ok. merged, and release in process.

**Pull request merged**
