### PR TITLE
Enable processor reloading in shells

### PR DESCRIPTION
**Pull request by kwalcock**
Account for reloading in shell menus and reload (i.e., create new processors) when requested. 

Nothing here yet accounts for locations of files.  It is likely that the exact same rules will be used upon reload.

### CODE REVIEW

**Comment by kwalcock** [comment]
Will do.

**Comment by kwalcock** [comment]
Here in in the just pushed commits is a second draft.  I'm not sure how the directory to support reading (reloading) rules from files should be specified.  In NumericEntityRecognizerShell, I just made it a command line argument.  Perhaps there should be a standard place like the current directory specified in a config file somewhere.

For the VariableShell and VariableProcessor in habitus, the same question applies.  There I also wonder which parts of the VariableProcessor should be reloaded.  There is a lexiconNer that might be changed and also an ExtractorEngine which relies on local files.  In VariableProcessor.apply there is a resource_dir which might serve as the hard-coded directory for reading those rules.  That directory only exists during development and would disappear upon deployment.  I'm not sure when the app will be used.

**Comment by kwalcock** [comment]
It looks like I still need to get the LexiconNER to load from files.  Those seem to only load from resources so far.  habitus is wanting that capability.

**Review by MihaiSurdeanu — APPROVED** [review]
Nice. Thank you @kwalcock!

Ok to merge.

**Pull request merged**
