### PR TITLE
Prevent Stanford NER from changing state

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This update to CHANGES.md probably needs to be coordinated with version.sbt.
I see some code in BioNLPUtils which may circumvent this fix.  I was just concerned for Eidos and did not check elsewhere.

**Comment by kwalcock** [comment]
I will run the REACH unit tests on this change before the merge takes place.

**Comment by kwalcock** [comment]
REACH is configured to use processors 6.3.0 and I had assumed that this change would be applied to the tip and therefore have no influence on REACH.  I've made this change to the older versions now and am observing failing tests, but have not been able to investigate.  Please do not merge yet.

**Comment by kwalcock** [comment]
It looks fine.  I tested under Linux and it ran without a hitch.  There may have been a problem on my machine with the Windows patches not being in 6.3.0 or something.  All clear.  It would be great to see this and the equality PR merged.

**Comment by MihaiSurdeanu** [comment]
Yes, please go ahead and merge it!

**Comment by kwalcock** [comment]
Sorry.  HAL says to me, "You're not authorized to merge this pull request."

**Comment by kwalcock** [comment]
I'm hoping to use these changes in Eidos soon and I see in CHANGES.md indications that they might be available.

7.2.2 - This is just a copy of 7.2.1, whose release on maven was broken
7.2.1 - Cross-compile for scala 2.11 and 2.12
7.2.1 - Prevented NER from changing state for the ShallowNLPProcessor and FastNLPProcessor
7.2.1 - Removed dependency to "edu.washington.cs.knowitall.nlptools" % "nlptools-stem-morpha_2.10", which was introducing dependency conflicts.

However, I get errors

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.clulab#processors-main_2.12;7.2.2: not found
[warn]  :: org.clulab#processors-corenlp_2.12;7.2.2: not found
[warn]  :: org.clulab#processors-odin_2.12;7.2.2: not found
[warn]  :: org.clulab#processors-modelsmain_2.12;7.2.2: not found
[warn]  :: org.clulab#processors-modelscorenlp_2.12;7.2.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

I don't see any release or tag at GitHub, so I'd be surprised if there was anything at Maven or elsewhere.  Maybe that will change soon.

**Comment by MihaiSurdeanu** [comment]
I'm working on it now...

**Pull request merged**
