### PR TITLE
Finally fixed incorrect dep graph sizes

### PR DESCRIPTION
**Pull request by MihaiSurdeanu**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@kwalcock: I believe this finally fixed that Eidos crash. Thanks for the examples!

**Comment by kwalcock** [comment]
This did seem to fix the problem.  The file 3_ALPAN_Paper_10.txt could be removed now.  Can this version be sent to maven?  It might be the version just before dynet goes parallel and it is a good fallback position if parallel goes wrong.  If it doesn't get published, people (I) would need to use the locally published version to get the fix.

**Comment by MihaiSurdeanu** [comment]
Good idea. Can you please release this?

**Comment by kwalcock** [comment]
It was just released.

**Comment by MihaiSurdeanu** [comment]
Nice, thanks!

**Pull request merged**
