### PR TITLE
Update dependencies and fatdynet model loading

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
It has been a long time since the loading logic was added to fatdynet.  If you have a handy model, it would be good to run it through this other code once just in case I don't remember it correctly.

**Comment by MihaiSurdeanu** [comment]
Will do!

**Comment by MihaiSurdeanu** [comment]
This looks good. I will check the model loading later tonight.

**Comment by MihaiSurdeanu** [comment]
Also, just FYI, checking model loading is trivial: run the ./shell script and choose the ":clu" processor. If it can parse a sentence, then things are Ok.

**Comment by MihaiSurdeanu** [comment]
@kwalcock: I checked. Everything seems to work. Please merge.

**Pull request merged**
