### PR TITLE
Add tissue type, reprioritize protein/families

### PR DESCRIPTION
**Pull request by hickst**
Part of Reach issue #170: Activate tissue type KB.
This branch depends on Bioresources version 1.1.6.
This branch increments the Processors version to 5.8.4.

### CODE REVIEW

**Comment by hickst** [comment]
Oh right...duh. This version will not pass checks until Bioresources 1.1.6 is available.

**Comment by MihaiSurdeanu** [comment]
Why is the build failing? Release bioresources first?

**Comment by hickst** [comment]
Closing and reopening to trigger tests.

**Comment by hickst** [comment]
Yes, my mistake in pulling too early. The processors build is now passing and can be merged and released.

**Pull request merged**
