### PR TITLE
Change to the new deberta model

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This shows how to change from the roberta to the deberta model.  However, using it will result in #21.

**Comment by MihaiSurdeanu** [comment]
Hey @kwalcock, any updates on this? Thank you!

**Comment by kwalcock** [comment]
I'm still digging deep into the Python code.  It is going to be difficult.  The most recent changes are in the [kwalcock/types](https://github.com/clulab/scala-transformers/tree/kwalcock/types) branch FWIW.

**Comment by MihaiSurdeanu** [comment]
That message is a warning, and it is possible that the tokens look similar. Did you compare the tokens produced by the Python and Rust tokenizers?

**Comment by MihaiSurdeanu** [comment]
In any case, if not all tokenizers are supported, it's not the end of the world. We just need to know, so we don't use the deberta model.

**Comment by kwalcock** [comment]
All of the output coming from Python matches whether the value for use_fast is True or False.  I'm assuming that False will result in the Python code running instead of Rust, but I have not yet seen exactly how that works.  So far all of it has matched the Rust code called from Scala as long as the tokenizer is one of those available directly from Rust.

**Comment by kwalcock** [comment]
The top tokenizers here (and maybe more) work from Scala via Rust without the stop in Python.  The trick will be to get the ones that include some kind of Python assistance to work.  Aren't the tokenizers paired with models so that this limits the models that can be used?

```scala
class SentencesTest extends Test {
  // See also test_clu_tokenizer.py.
  val tokenizerNames = Seq(
    "bert-base-cased",
    "distilbert-base-cased",
    "roberta-base",
    "xlm-roberta-base" // ,
    // All of these latter ones will not just fail, but cause a
    // fatal runtime error and end the testing completely.
    // "google/bert_uncased_L-4_H-512_A-8",
    // "google/electra-small-discriminator",
    // "microsoft/deberta-v3-base"
  )
```

**Comment by MihaiSurdeanu** [comment]
Yes, limiting the tokenizers will limit the models we have access to. In particular, deberta is an important one for processors.
I wonder if we do the same trick we did with Breeze. That is, replicate the Python parts directly in Scala. Is that complicated?

**Comment by MihaiSurdeanu** [comment]
Nice!! Ok to merge?

**Comment by kwalcock** [comment]
Yes.  Just finished testing.

**Comment by MihaiSurdeanu** [comment]
This works great!

**Pull request merged**
