### PR TITLE
Save and load the RNN model

### PR DESCRIPTION
**Pull request by kwalcock**
This is an updated version which does not use fatdynet to save or load.  The model can be saved, loaded, and resaved resulting in a bitwise identical file.  Evaluation runs across the dev training sentences result in matching values.  Some test code remains so that runs can be made in reasonable times, so do look at the changes.  Some code was rearranged so that the RNNParameters could be set either by training or by loading.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock!
This looks good. But can you please merge the dynet-rnn branch into this again? There were some changes there since this branch was created.

**Comment by kwalcock** [comment]
I *think* that I beat you to it.  This PR is for kwalcock-rnn2 which is only one push ahead of dynet-rnn and no pull behind.  The old kwalcock-rnn was closed without a merge.

**Comment by MihaiSurdeanu** [comment]
Cool. Then, merge?

**Comment by kwalcock** [comment]
For testing in a reasonable time I commented out a few lines.  I'm not sure whether you want them changed back or not before a merge.  Otherwise it is OK.

**Comment by MihaiSurdeanu** [comment]
That's fine. Should I merge then in mybranch, so I can play with it, extend it, etc?

**Comment by kwalcock** [comment]
Sounds good.

**Comment by MihaiSurdeanu** [comment]
But is this PR for merge into *master*? Then, I think we should wait a bit. 
I am merging it into dynet-rnn for now.

**Comment by kwalcock** [comment]
Just to your branch, the work in progress, as it seemed to have happened.  Thanks.

**Pull request merged**
