### PR TITLE
Calculate roots automatically

### PR DESCRIPTION
**Pull request by kwalcock**
This still has roots passed in, usually as an empty Seq, for testing.  It will be removed shortly.  Several tests in clulab.utils.TestDependencyUtils are failing.  The ones I looked at should be failing given the new definition of root.  The old definition may have been slightly different.  It looks like lone vertices, with no incoming or outgoing edges, were not always considered to be roots before.  They are now.  I'm not sure what to do about the tests.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Can you please list the failing tests here?

**Comment by kwalcock** [comment]
1.  text1 should "produce 'substrates' as the head of 'the substrates of Shp2'" in {
1.   it should "produce 'are' as the head of 'the substrates of Shp2 are'" in {
1.   text2 should "have the same getHeadStrict as roots" in {  text2 should "have the same getHeadStrict as roots" in {

I will be looking more closely very soon.

**Comment by kwalcock** [comment]
For sent1, the edges are as below.  Previously, the roots were just [15], but now they are [3 6 11 15 16 20 24 26 35 40 41 45 49] because the other nodes aren't touched.
```
2 -> 1
2 -> 4
5 -> 0
5 -> 2
5 -> 9
9 -> 7
9 -> 8
9 -> 10
15 -> 31
15 -> 17
15 -> 5
15 -> 12
15 -> 13
15 -> 14
17 -> 19
19 -> 18
19 -> 23
23 -> 21
23 -> 22
23 -> 25
25 -> 27
31 -> 47
31 -> 28
31 -> 29
31 -> 30
34 -> 33
34 -> 36
36 -> 38
36 -> 43
38 -> 37
38 -> 39
38 -> 43
43 -> 42
43 -> 44
47 -> 32
47 -> 48
47 -> 34
47 -> 46
48 -> 51
51 -> 50
```

**Comment by kwalcock** [comment]
Similarly, for sent2, roots were [10] but now they are [8 10 12 15].  Edges are
```
3 -> 0
3 -> 1
3 -> 2
7 -> 3
7 -> 4
7 -> 5
7 -> 6
7 -> 9
10 -> 19
10 -> 7
10 -> 11
11 -> 18
11 -> 14
14 -> 18
14 -> 13
18 -> 16
18 -> 17
```

**Comment by MihaiSurdeanu** [comment]
The new outputs are the correct ones. The tests should be adjusted.

**Comment by kwalcock** [comment]
This has been superseded.

**Pull request closed without merging**
