### PR TITLE
fixed bug in lazy quantifiers

### PR DESCRIPTION
**Pull request by marcovzla**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Can you please also update CHANGES for 7.5.0?

**Comment by MihaiSurdeanu** [comment]
Ok to release now?

**Comment by marcovzla** [comment]
i think so
@myedibleenso ?

**Comment by myedibleenso** [comment]
Yes.  Would be nice to have even more tests, but at least we have a one : )

**Comment by MihaiSurdeanu** [comment]
@kwalcock: can you please release? You have the permissions, right?

**Comment by kwalcock** [comment]
I believe so.  Will wait for that one last approved merge.

**Pull request merged**
