### PR TITLE
Issue #124: enhance NER to load Phase3 override KB

### PR DESCRIPTION
**Pull request by hickst**
Enhance NER to load multiple override files. Update to use Bioresources 1.1.20 containing MITRE PhaseIII override KB.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
This is good, but I wonder if we can come up with a naming convention for the override files. Phase3-Override.tsv.gz seems very arbitrary... Maybe we can have NER-Grounding-Override-ddd.tsv.gz, where the ddd indicates the priority in loading (the smaller the number the higher the priority)?

**Comment by hickst** [comment]
Sure, that sounds fine but there are some other considerations with this file that we should discuss at our weekly meeting tomorrow.

**Comment by hickst** [comment]
I just re-merged master into this branch **after** starting the pull request, then pushed again. I am hoping that Travis will do the right thing and restart the PR tests?

**Comment by hickst** [comment]
Restart Travis testing.

**Pull request closed without merging**
