### PR TITLE
Clean tokens when parsing numeric expressions.

### PR DESCRIPTION
**Pull request by marcovzla**
Converts to lowercase and remove commas.
Fixes an issue mentioned in #530

### CODE REVIEW

**Comment by marcovzla** [comment]
Fixes #530 
@MihaiSurdeanu fyi

**Comment by MihaiSurdeanu** [comment]
@marcovzla: tests still fail...

**Comment by MihaiSurdeanu** [comment]
Thanks @marcovzla ! This seems fine logically to me.
Let's see if the tests pass.

**Comment by MihaiSurdeanu** [comment]
@kwalcock : if you haven't released, please wait until this is merged.

**Comment by MihaiSurdeanu** [comment]
Hi @marcovzla,
One test seems to be failing:
```
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	org.clulab.processors.TestCluProcessor
[error] (main / Test / test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by kwalcock** [comment]
OK.  I will hold off on the release.  The other failing test is fixed in the meantime.

**Comment by MihaiSurdeanu** [comment]
Thanks @marcovzla! All good now.

**Pull request merged**
