### PR TITLE
Add new FamilyOrComplex NER label

### PR DESCRIPTION
**Pull request by bgyori**
Related to https://github.com/clulab/bioresources/pull/27

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@bgyori: Do you want me to run these tests, or are you doing it now?

**Comment by bgyori** [comment]
Before I can run the tests, I need to get ner/FamilyOrComplex.tsv.gz to be generated in bioresources. After adding this line to the conf file, I am getting an error saying
```
[error] (run-main-0) java.lang.RuntimeException: ERROR: cannot find resource org/clulab/reach/kb/ner/FamilyOrComplex.tsv.gz in classpath!
```
Is there some other place the FamilyOrComplex label needs to be defined?

**Comment by MihaiSurdeanu** [comment]
You have to first run "sbt publishLocal" in that branch in bioresources. And adjust the bioresources version to "1.1.30-SNAPSHOT" here in this processors branch.

(After we merge this branch, I will fix this dependency nightmare, by moving both bioresources and BioNLPProcessors as subprojects under reach. This would mean that any adjustments to KBs happen  just in reach and are immediately visible.)

**Comment by bgyori** [comment]
I will close this PR since we have changed course and will not introduce a FamilyOrComplex label.

**Pull request closed without merging**
